"""initial schema

Revision ID: 40b93348596d
Revises: 
Create Date: 2026-04-28 03:53:36.430164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40b93348596d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.Column('mood', sa.Text(), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('tracks_played', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('file_mtime', sa.Float(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('last_played', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index('idx_tracks_artist', ['artist'], unique=False)
        batch_op.create_index('idx_tracks_genre', ['genre'], unique=False)
        batch_op.create_index('idx_tracks_play_count', ['play_count'], unique=False)

    op.create_table('daily_stats',
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('skip_count', sa.Integer(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('date', 'track_id')
    )
    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.create_index('idx_queue_position', ['position'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.Float(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_index('idx_queue_position')

    op.drop_table('queue')
    op.drop_table('playlist_tracks')
    op.drop_table('daily_stats')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('idx_tracks_play_count')
        batch_op.drop_index('idx_tracks_genre')
        batch_op.drop_index('idx_tracks_artist')

    op.drop_table('tracks')
    op.drop_table('sessions')
    op.drop_table('playlists')
    # ### end Alembic commands ###
